{% set name = "gds-sigp" %}
{% set version = "1.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/software/gds-sigp/-/archive/{{ version }}/{{ version }}.tar.gz
  sha256: 67935ed82fc9b99acff9df2c0071ab3d69036d593e74b1cd4b471140941b5ad0

build:
  error_overlinking: true
  error_overdepending: true
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('gds-sigp', max_pin='x.x') }}

requirements:
  build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - {{ stdlib("c") }}
   - cmake
   - make  # [not win]
   - pkg-config  # [not win]

  host:
   - fftw
   - expat
   - libexpat
   - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libgds-sigp${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/include/gds-sigp/gdssigproc.h  # [unix]

about:
  home: https://git.ligo.org/cds/software/gds_sigp
  dev_url: https://git.ligo.org/cds/software/gds_sigp.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: Library for advinced LIGO signal processing

extra:
  recipe-maintainers:
    - evonreis
